In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
import numpy as np
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + " ms.")

c= 0
tic =time.time()
for i in range(1000000):
    c += a[i] *b[i]
toc =time.time()
print("For loop: " + str(1000*(toc-tic)) + " ms")

249765.92386182921
Vectorized version: 0.57220458984375 ms.
For loop: 435.2099895477295 ms


In [4]:
import numpy as np
A= np.array([
    [56.0,0.0,4.4,68.0],
    [1.2,104.0,52.0,8.0],
    [1.8,135.0,99.0,0.9]
])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [9]:
percentage =100 * A/ cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
