In [1]:
import numpy as np
# 生成对角矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

NumPy 最重要的一个特点是其N维数组对象ndarray，它是一系列同类型数据的集合，以0下标为开始进行集合中元素的索引。

ndarray 对象是用于存放同类型元素的多维数组。
ndarray 中的每个元素在内存中都有相同存储大小的区域。

ndarray 内部由以下内容组成：

* 一个指向数据（内存或内存映射文件中的一块数据）的指针。

* 数据类型或dtype，描述在数组中的固定大小值的格子。

* 一个表示数组形状（shape）的元组，表示各维度大小的元组。

* 一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要"跨过"的字节数。

ndarray的内部数据结构：
![](http://www.runoob.com/wp-content/uploads/2018/10/ndarray.png)

跨度可以是负数，这样会使数组在内存中后移动，切片中obj[::-1]或obj[:,::-1]就是如此

创建一个 ndarray 只需调用 NumPy 的 array 函数即可：
```
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
参数说明：
- object 数组或者嵌套的数列
- dtype  数组元素的数据类型，可选
- copy   对象是否需要复制，可选
- order  创建数组的样式，C为行方向，F为列方向，A为任意方向，（默认）
- subok  默认返回一个与基类类型一致的数组
- ndmin  指定申城数组的最小维度   

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
## 多一个维度
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
# 最小维度
a  = np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [5]:
# DTYPE 参数
a = np.array([1,2,3,4],dtype=int)
print(a)
print(12)

[1 2 3 4]
12


## Numpy数组属性

In [6]:
# ndarray.ndim 秩，即轴的数量或维度的数量

a = np.arange(24)
print(a.ndim) # a现在|只有一个维度
print(a)
# 调整维度
b =a.reshape(2,4,3)
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [7]:
# ndarray.shape
# 表示数组的维度，返回一个元祖，这个元祖的长度就是维度的数据，即ndim属性。比如，一个二维数组，
# 其维度表示行数和列数
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

# 使用shape调整数组大小
a.shape = (3,2)
print(a)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [8]:
# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小

x = np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

y = np.array([1,2,3,4,5],dtype=np.float64)
print(y.itemsize)

1
8


## 创建数组

In [9]:
# 1. numpu.empty()
# 创建一个制定形状shape，数据类型切未初始化的数组
#  numpy.empty(shape, dtype = float, order = 'C')

c = np.empty([3,2],dtype=int)
print(c)

# np.zeros
# 创建制定大小的数组，数组元素以0来填充
x= np.zeros(5)
print(x)


# numpy.ones
# 创建指定形状的数组，数组元素以 1 来填充：

x= np.ones(5)
print(x)

## 从已有的数组中穿件数组
x = [1,2,3]
a = np.asarray(x)
print(a)

x = (1,2,3)
a  = np.asarray(x)
print(a)

# 从数值范围创建数组
# numpy.arange(start, stop, step, dtype)
x = np.arange(5)
print(x)

x = np.arange(5,dtype=float)
print(x)

x = np.arange(10,20,2)
print(x)


[[0 0]
 [0 0]
 [0 0]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3]
[1 2 3]
[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]


## 切片

In [10]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

# 切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print(a)
print()
print(a[...,1]) # 打印第二列元素
print(a[1,...]) # 打印第二行元素
print(a[...,1:]) # 打印第二列及以后元素
print(a[1:,...]) # 打印第二行及以后元素

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]
[[3 4 5]
 [4 5 6]]


In [14]:
# 整数数组索引
x = np.array([[1,  2],  [3,  4],  [5,  6]]) 
## 获取数组中 [0,0],(1,1),(2,0)处的位置元素
y = x[[0,1,1],[0,1,0]]
print(y)
# 获取4x3四个角的元素
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：' )
print (x)
print ('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print  ('这个数组的四个角元素是：')
print (y)

[1 4 3]
我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


In [16]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a)
b = a[1:3, 1:3]
c = a[1:3,[1,2]]
d = a[...,1:]
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [18]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])  
print ('我们的数组是：')
print (x)
print ('\n')
# 打印大于5的元素
print("大于5的元素是：")
print(x[x>5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于5的元素是：
[ 6  7  8  9 10 11]


## 广播 Boardcast

广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。

如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。

In [19]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print(c)

[ 10  40  90 160]


In [21]:
# 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：
a = np.array([
     [0,0,0],
     [10,10,10],
     [20,20,20],
     [30,30,30]
 ])
b = np.array([1,2,3])
c = a * b
print(c)

[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


下面的图片展示了数组 b 如何通过广播来与数组 a 兼容。
![](http://www.runoob.com/wp-content/uploads/2018/10/image0020619.gif)

In [23]:
# 4x3 的二维数组与长为 3 的一维数组相加，等效于把数组 b 在二维上重复 4 次再运算：
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
bb = np.tile(b,(4,1))
print(bb)
## 上下俩个相等
print(a+bb)
print(a+b)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


## 迭代数组


NumPy 迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。

迭代器最基本的任务的可以完成对数组元素的访问。

接下来我们使用 arange() 函数创建一个 2X3 数组，并使用 nditer 对它进行迭代。

In [25]:
a = np.arange(6).reshape(2,3)
print("原始数组是：")
print(a)
print("\n")
print("迭代输出元素：")
for x in np.nditer(a):
    print(x,end=",")
print("\n")


原始数组是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
0,1,2,3,4,5,



In [28]:
for x in np.nditer(a.T):
    print(x,end=", ")
print("\n")

for x in np.nditer(a.T.copy(order="C")):
    print(x,end=", ")
print("\n")

0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



### 修改数组形状

### reshape 不改变数据的情况下修改形状
numpy.reshape 函数可以在不改变数据的条件下修改形状，格式如下： numpy.reshape(arr, newshape, order='C')
* arr：要修改形状的数组
* newshape：整数或者整数数组，新的形状应当兼容原有形状
* order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'k' -- 元素在内存中的出现顺序。

In [29]:
a = np.arange(8)
print ('原始数组：')
print (a)
print ('\n')

b = a.reshape(4,2)
print(b)

原始数组：
[0 1 2 3 4 5 6 7]


[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [31]:
# numpy.ndarray.flat 是一个数组元素迭代器，实例如下:
a = np.arange(9).reshape(3,3)
print("元是数组")
for row in a:
    print(row)

## 对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器
for element in a .flat:
    print(element)

元是数组
[0 1 2]
[3 4 5]
[6 7 8]
0
1
2
3
4
5
6
7
8


In [33]:
# numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：
a = np.arange(8).reshape(2,4)
print("原数组")
print(a)
print(a)

print("展开数的数组：")
print(a.flatten())
print("\n")

print("以F风格展开")
print(a.flatten(order='F'))




原数组
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
展开数的数组：
[0 1 2 3 4 5 6 7]


以F风格展开
[0 4 1 5 2 6 3 7]


In [35]:
# numpy.ravel
# numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），修改会影响原始数组。

# 该函数接收两个参数：
# numpy.ravel(a, order='C')

a = np.arange(8).reshape(2,4)
print("原数组：")
print(a)
print("\n")

print("调用ravel函数之后")
print(a.ravel())
print("\n")

print("以F风格顺序调用ravel函数之后")
print(a.ravel(order='F'))


原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用ravel函数之后
[0 1 2 3 4 5 6 7]


以F风格顺序调用ravel函数之后
[0 4 1 5 2 6 3 7]
[[0 1 2 3]
 [4 5 6 7]]


In [38]:
## 修改数组维度
# numpy.broadcast 用于模仿广播的对象，它返回一个对象，该对象封装了将一个数组广播到另一个数组的结果。

# 该函数使用两个数组作为输入参数，如下实例：
x = np.array([[1],[2],[3]])
y = np.array([4,5,6])

# 对 y 广播 x
b = np.broadcast(x,y)  

# 它拥有 iterator 属性，基于自身组件的迭代器元组 
print ('对 y 广播 x：')
r,c = b.iters
 
# Python3.x 为 next(context) ，Python2.x 为 context.next()
print (next(r), next(c))
print (next(r), next(c))
print ('\n')
# shape 属性返回广播对象的形状

对 y 广播 x：
1 4
1 5


