In [1]:
import tensorflow as tf

def demo1():
    v1 = tf.get_variable("v1",shape=[3],initializer=tf.zeros_initializer)
    v2 = tf.get_variable("v2",shape=[5],initializer=tf.zeros_initializer)   
    
    inc_v1 = v1.assign(v1+1)
    dec_v2 = v2.assign(v2-1)

    # Add an op to initialize the variables.
    init_op = tf.global_variables_initializer()

    # Add ops to save and restore all the variables.
    saver = tf.train.Saver()

    # Later, launch the model, initialize the variables, do some work, and save the
    # variables to disk.
    with tf.Session() as sess:
          sess.run(init_op)
          # Do some work with the model.
          inc_v1.op.run()
          dec_v2.op.run()
          # Save the variables to disk.
          save_path = saver.save(sess, "/tmp/model.ckpt")
          print("Model saved in path: %s" % save_path)


In [5]:
def restore_model():
    tf.reset_default_graph()
    # create some variables
    v1 = tf.get_variable("v1",shape=[3])
    v2 = tf.get_variable("v2",shape=[5])
    
#     add ops to save and restore all the variables
    saver = tf.train.Saver()
#     later ,launch the model,use the saver to restore varibales from disk and
#    do some work with the model
    with tf.Session() as sess:
#         restore variables from disk 
        saver.restore(sess,"/tmp/model.ckpt")
        print("model restored.")
#         check the values of the variables
        print("v1:%s" % v1.eval())
        print("v2:%s" % v2.eval())
# demo1()
restore_model()

INFO:tensorflow:Restoring parameters from /tmp/model.ckpt
model restored.
v1:[1. 1. 1.]
v2:[-1. -1. -1. -1. -1.]


In [9]:
def restore_model_part():
    tf.reset_default_graph()
#     create somevariables
    v1 = tf.get_variable("v1",[3],initializer=tf.zeros_initializer)
    v2 = tf.get_variable("v2",[5],initializer=tf.zeros_initializer)
#     add ops to save and restore only 'v2' using the name v2
    saver = tf.train.Saver({"v2":v2})
    with tf.Session() as sess:
#         initialize v1 since the saver will not
        v1.initializer.run()
        saver.restore(sess,"/tmp/model.ckpt")
        print("v1 : %s" % v1.eval())
        print("v2 : %s" % v2.eval())
save_model_part()

INFO:tensorflow:Restoring parameters from /tmp/model.ckpt
v1 : [0. 0. 0.]
v2 : [-1. -1. -1. -1. -1.]


In [10]:
from tensorflow.python.tools import inspect_checkpoint as chkp
def inspect_checkpoint_demo():
    # print all tensor in checkpoint file
    chkp.print_tensors_in_checkpoint_file("/tmp/model.ckpt",tensor_name="",all_tensors=True)
     # tensor_name:  v1
    # [ 1.  1.  1.]
    # tensor_name:  v2
    # [-1. -1. -1. -1. -1.]
    
    #print only tensor v1 in checkpoint file
    chkp.print_tensors_in_checkpoint_file("/tmp/model.ckpt",tensor_name="v1",all_tensors=False)
    
    # tensor_name: v1 
    # [1. 1. 1.]
    
inspect_checkpoint_demo()    

tensor_name:  v1
[1. 1. 1.]
tensor_name:  v2
[-1. -1. -1. -1. -1.]
tensor_name:  v1
[1. 1. 1.]
