In [2]:
import numpy as np
# 生成对角矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

NumPy 最重要的一个特点是其N维数组对象ndarray，它是一系列同类型数据的集合，以0下标为开始进行集合中元素的索引。

ndarray 对象是用于存放同类型元素的多维数组。
ndarray 中的每个元素在内存中都有相同存储大小的区域。

ndarray 内部由以下内容组成：

* 一个指向数据（内存或内存映射文件中的一块数据）的指针。

* 数据类型或dtype，描述在数组中的固定大小值的格子。

* 一个表示数组形状（shape）的元组，表示各维度大小的元组。

* 一个跨度元组（stride），其中的整数指的是为了前进到当前维度下一个元素需要"跨过"的字节数。

ndarray的内部数据结构：
![](http://www.runoob.com/wp-content/uploads/2018/10/ndarray.png)

跨度可以是负数，这样会使数组在内存中后移动，切片中obj[::-1]或obj[:,::-1]就是如此

创建一个 ndarray 只需调用 NumPy 的 array 函数即可：
```
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```
参数说明：
- object 数组或者嵌套的数列
- dtype  数组元素的数据类型，可选
- copy   对象是否需要复制，可选
- order  创建数组的样式，C为行方向，F为列方向，A为任意方向，（默认）
- subok  默认返回一个与基类类型一致的数组
- ndmin  指定申城数组的最小维度   

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
## 多一个维度
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [5]:
# 最小维度
a  = np.array([1,2,3,4,5],ndmin=2)
print(a)

[[1 2 3 4 5]]


In [10]:
# DTYPE 参数
a = np.array([1,2,3,4],dtype=int)
print(a)
print(12)

[1 2 3 4]
12


## Numpy数组属性

In [13]:
# ndarray.ndim 秩，即轴的数量或维度的数量

a = np.arange(24)
print(a.ndim) # a现在|只有一个维度
print(a)
# 调整维度
b =a.reshape(2,4,3)
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [17]:
# ndarray.shape
# 表示数组的维度，返回一个元祖，这个元祖的长度就是维度的数据，即ndim属性。比如，一个二维数组，
# 其维度表示行数和列数
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

# 使用shape调整数组大小
a.shape = (3,2)
print(a)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [20]:
# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小

x = np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

y = np.array([1,2,3,4,5],dtype=np.float64)
print(y.itemsize)

1
8


## 创建数组

In [29]:
# 1. numpu.empty()
# 创建一个制定形状shape，数据类型切未初始化的数组
#  numpy.empty(shape, dtype = float, order = 'C')

c = np.empty([3,2],dtype=int)
print(c)

# np.zeros
# 创建制定大小的数组，数组元素以0来填充
x= np.zeros(5)
print(x)


# numpy.ones
# 创建指定形状的数组，数组元素以 1 来填充：

x= np.ones(5)
print(x)

## 从已有的数组中穿件数组
x = [1,2,3]
a = np.asarray(x)
print(a)

x = (1,2,3)
a  = np.asarray(x)
print(a)

# 从数值范围创建数组
# numpy.arange(start, stop, step, dtype)
x = np.arange(5)
print(x)

x = np.arange(5,dtype=float)
print(x)

x = np.arange(10,20,2)
print(x)


[[31660752        0]
 [       0        0]
 [       0        0]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3]
[1 2 3]
[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]


## 切片

In [40]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

# 切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print(a)
print()
print(a[...,1]) # 打印第二列元素
print(a[1,...]) # 打印第二行元素
print(a[...,1:]) # 打印第二列及以后元素
print(a[1:,...]) # 打印第二行及以后元素

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]
[[3 4 5]
 [4 5 6]]
